version: 2

models:
  - name: stg_products
    config:
      schema: "{{env_var('DBT_STAGESCHEMA','STAGING')}}"

  - name: stg_orders
    config:
      schema: "{{env_var('DBT_STAGESCHEMA','STAGING')}}"
  