version: 2

seeds:
  - name: divisions
    config:
      schema: "{{env_var('DBT_SEEDSCHEMA','LOOKUP')}}"

  - name: categories
    config:
      schema: "{{env_var('DBT_SEEDSCHEMA','LOOKUP')}}"

  - name: shippers
    config:
      schema: "{{env_var('DBT_SEEDSCHEMA','LOOKUP')}}"